### PR TITLE
scipy 0.16.0

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by tdsmith** [comment]
Dunno why this is broken; seems like a numpy.distutils issue!?

**Comment by tdsmith** [comment]
0.15.1 builds fine so perhaps there's something newly misbehaving in scipy.

**Comment by John-Colvin** [comment]
No idea, it builds fine locally for me on 2 different machines.

**Comment by tdsmith** [comment]
Can you paste the logs from a successful build with `brew gist-logs scipy`?

**Pull request closed without merging**
