### PR TITLE
python-mako 1.0.6 (new formula)

### PR DESCRIPTION
**Pull request by parcollet**
New formula to install the mako template library for Python.

### CODE REVIEW

**Comment by parcollet** [comment]
1) Fails on Sierra. Why ?

==>Verifying python--wheel-0.29.0.tar.gz checksum
tar xzf /Users/brew/Library/Caches/Homebrew/python--wheel-0.29.0.tar.gz
Error: No available formula with the name "homebrew/dupes/tcl-tk" 
Please tap it and then try again: brew tap homebrew/dupes
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

2) Why is the test recompiling python ? Shouldn't it simply use the bottle for it ?

**Comment by tdsmith** [comment]
This doesn't have any Homebrew dependencies; this looks like something pip should handle fine. What's the advantage of writing a formula for this?

**Comment by parcollet** [comment]
Yes it is very simple, and pip does it too easily.
However: 

- I thought the point of a package system was to package everything, uniformly.
  I do it to have the last dependency of the new "triqs" formula (in science tap)
  in brew as well. 
  Otherwise I have to add "pip install mako" in the installation procedure, 
  and I would have my triqs formula installing something with pip silently.
  Is that good practice ?

- Still, it does not work ! On Sierra, because it recompiles python and this breaks ...

**Comment by tdsmith** [comment]
Homebrew doesn't aim to repackage pypi. The way we manage Python dependencies of libraries is to:

Declare them as a resource: https://github.com/Homebrew/homebrew-python/blob/master/numpy.rb#L34-L37

Install them to a private prefix and write a helper .pth: https://github.com/Homebrew/homebrew-python/blob/master/numpy.rb#L64-L71

test-bot looks broken but I don't have the tuits to troubleshoot.

**Pull request closed without merging**
