### PR TITLE
matplotlib 1.5.0

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
```
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/matplotlib/1.5.0/libexec --single-version-externally-managed --record=installed.txt
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "setup.py", line 10, in <module>
    setuptools_installed = StrictVersion(setuptools.__version__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '0.6c12'
```

**Comment by tdsmith** [comment]
looks like setuptools needs to be vendored

**Comment by CodingAnarchy** [comment]
Any update on this?  I don't want to spend effort replicating work that is already done.

**Comment by bfontaine** [comment]
@CodingAnarchy I’ll try something today.

**Comment by bfontaine** [comment]
It now builds but the test fails:
```
==> python -c import matplotlib as m; m.test()
matplotlib.test requires nose and mock to run.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1503, in test
    verify_test_dependencies()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1495, in verify_test_dependencies
    import mock
  File "/usr/local/Cellar/matplotlib/1.5.0/libexec/lib/python2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/local/Cellar/matplotlib/1.5.0/libexec/lib/python2.7/site-packages/mock/mock.py", line 68, in <module>
    from six import wraps
ImportError: cannot import name wraps
```

**Comment by tdsmith** [comment]
Cycler is a (new?) dependency; the resources should look like:

```ruby
  resource "Cycler" do
    url "https://pypi.python.org/packages/source/C/Cycler/cycler-0.9.0.tar.gz"
    sha256 "96dc4ddf27ef62c09990c6196ac1167685e89168042ec0ae4db586de023355bc"
  end

  resource "funcsigs" do
    url "https://pypi.python.org/packages/source/f/funcsigs/funcsigs-0.4.tar.gz"
    sha256 "d83ce6df0b0ea6618700fe1db353526391a8a3ada1b7aba52fed7a61da772033"
  end

  resource "nose" do
    url "https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz"
    sha256 "f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98"
  end

  resource "mock" do
    url "https://pypi.python.org/packages/source/m/mock/mock-1.3.0.tar.gz"
    sha256 "1e247dbecc6ce057299eb7ee019ad68314bb93152e81d9a6110d35f4d5eca0f6"
  end

  resource "pbr" do
    url "https://pypi.python.org/packages/source/p/pbr/pbr-1.8.1.tar.gz"
    sha256 "e2127626a91e6c885db89668976db31020f0af2da728924b56480fc7ccf09649"
  end

  resource "pyparsing" do
    url "https://pypi.python.org/packages/source/p/pyparsing/pyparsing-2.0.6.tar.gz"
    sha256 "aea69042752ad7e9c436eea6ae5d40e73642e27f50edb6da4a2532030ef532da"
  end

  resource "python-dateutil" do
    url "https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.2.tar.gz"
    sha256 "3e95445c1db500a344079a47b171c45ef18f57d188dffdb0e4165c71bea8eb3d"
  end

  resource "pytz" do
    url "https://pypi.python.org/packages/source/p/pytz/pytz-2015.7.tar.bz2"
    sha256 "fbd26746772c24cb93c8b97cbdad5cb9e46c86bbdb1b9d8a743ee00e2fb1fc5d"
  end

  resource "six" do
    url "https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz"
    sha256 "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a"
  end
```

(mock wants funcsigs and pbr)

**Comment by tdsmith** [comment]
(oh, plus setuptools)

**Comment by bfontaine** [comment]
Thanks @tdsmith I fixed the resources.

I added the following in the test: `system python, "-c", "import six; print(six.__file__)"`. The first time I ran it it printed the following then failed:
```
/usr/local/lib/python2.7/site-packages/six.pyc
```

I removed this file to see what would happen and then re-ran the test. I got this output:
```
/usr/local/lib/python2.7/site-packages/six.py
```

…followed by a test running for a while then dying in an horrible way:

```
==> python -c import matplotlib as m; m.test()
.......K.KKK....K..K......K....K..K..K..K......K..K..K..K....K...........................K..K..K..K....K..K..K..K..K..K..K..K....K...K..K..K..K..K..K......K..K..K...K..K..K..K..K..K..K..K..K.......K.........K..K..K..K......K....K..K..K..K..K..K...K..K..K....K............K..K..K..K..K..K..K..K..K..K......K....K...K..K..K..K..............K..K..K..K..K..K..K..K..K.....K............................................................SSSSSS.sh: latex: command not found
Ksh: latex: command not found
K..../usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:1287: UserWarning: findfont: Font family [u'Bitstream Vera Sans'] not found. Falling back to Helvetica
  (prop.get_family(), self.defaultFamily[fontext]))
.KKKKKKKKKKKKKKKKKKKKKKKKKKK..K....K...K..K..K..K........................FK...K..K..K..K..K..K..K..K..K..K..K..K..K..K............./usr/local/lib/python2.7/site-packages/matplotlib/collections.py:360: UserWarning: Collection picker None could not be converted to float
  % self._picker)
.....K.....................................K../usr/local/lib/python2.7/site-packages/matplotlib/colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4
  colors = np.asarray(colors)[igood]
/usr/local/lib/python2.7/site-packages/matplotlib/colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3
  colors = np.asarray(colors)[igood]
==> Sandbox log
Nov 26 01:37:43 kernel[0]: Sandbox: Python(10708) deny(1) file-write-create /usr/local/lib/python2.7/site-packages/six.pyc
Nov 26 01:37:43 kernel[0]: Sandbox: Python(10709) deny(1) file-write-create /usr/local/lib/python2.7/site-packages/six.pyc
Nov 26 01:37:43 kernel[0]: Sandbox: Python(10709) deny(1) file-write-create /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hotshot/__init__.pyc
Nov 26 01:37:43 kernel[0]: Sandbox: Python(10709) deny(1) file-write-create /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hotshot/stats.pyc
Nov 26 01:37:43 kernel[0]: Sandbox: Python(10709) deny(1) file-write-create /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/profile.pyc
Nov 26 01:37:44 kernel[0]: Sandbox: Python(10709) deny(1) file-write-create /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pstats.pyc
Nov 26 01:37:44 kernel[0]: Sandbox: Python(10709) deny(1) file-write-create /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hotshot/log.pyc
Nov 26 01:37:46 kernel[0]: Sandbox: Python(10709) deny(1) file-write-create /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/timeit.pyc
Nov 26 01:37:46 kernel[0]: Sandbox: Python(10709) deny(1) file-write-create /usr/local/lib/python2.7/site-packages/numpy/ma/testutils.pyc
Nov 26 01:42:20 kernel[0]: Sandbox: Python(10709) deny(1) file-write-create /usr/local/lib/python2.7/site-packages/numpy/dual.pyc
Error: homebrew/python/matplotlib: failed
```

**Comment by tdsmith** [comment]
I actually don't see the failure? Those are all non-fatal warnings; there's one test failure but it doesn't seem to be associated with any of the messages on stdout. The latex invocation is allowed to fail; the sandbox messages are just informative and can be ignored. I'll look at this later.

**Comment by bfontaine** [comment]
With the `PYTHONDONTWRITEBYTECODE` it gives this:

```
==> python -c import matplotlib as m; m.test()
.......K.KKK....K..K......K....K..K..K..K......K..K..K..K....K...........................K..K..K..K....K..K..K..K..K..K..K..K....K...K..K..K..K..K..K......K..K..K...K..K..K..K..K..K..K..K..K.......K.........K..K..K..K......K....K..K..K..K..K..K...K..K..K....K............K..K..K..K..K..K..K..K..K..K......K....K...K..K..K..K..............K..K..K..K..K..K..K..K..K.....K............................................................SSSSSS.sh: latex: command not found
Ksh: latex: command not found
K..../usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:1287: UserWarning: findfont: Font family [u'Bitstream Vera Sans'] not found. Falling back to Helvetica
  (prop.get_family(), self.defaultFamily[fontext]))
.KKKKKKKKKKKKKKKKKKKKKKKKKKK..K....K...K..K..K..K........................FK...K..K..K..K..K..K..K..K..K..K..K..K..K..K............./usr/local/lib/python2.7/site-packages/matplotlib/collections.py:360: UserWarning: Collection picker None could not be converted to float
  % self._picker)
.....K.....................................K../usr/local/lib/python2.7/site-packages/matplotlib/colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4
  colors = np.asarray(colors)[igood]
/usr/local/lib/python2.7/site-packages/matplotlib/colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3
  colors = np.asarray(colors)[igood]
==> Sandbox log
Nov 26 01:46:24 kernel[0]: Sandbox: navd(79753) deny(1) file-read-data /Users/baptiste/Library/Preferences/com.apple.security.revocation.plist
Nov 26 01:46:35 kernel[0]: Sandbox: navd(79753) deny(1) file-read-data /Users/baptiste/Library/Preferences/com.apple.security.revocation.plist
Nov 26 01:46:35 kernel[0]: Sandbox: navd(79753) deny(1) file-read-data /Users/baptiste/Library/Preferences/com.apple.security.revocation.plist
Error: homebrew/python/matplotlib: failed
execution expired
/usr/local/Library/Homebrew/formula.rb:1402:in `gets'
/usr/local/Library/Homebrew/formula.rb:1402:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1375:in `open'
/usr/local/Library/Homebrew/formula.rb:1375:in `system'
/usr/local/Library/Taps/homebrew/homebrew-python/matplotlib.rb:190:in `block (2 levels) in <class:Matplotlib>'
/usr/local/Library/Homebrew/language/python.rb:25:in `call'
/usr/local/Library/Homebrew/language/python.rb:25:in `block in each_python'
/usr/local/Library/Homebrew/language/python.rb:17:in `each'
/usr/local/Library/Homebrew/language/python.rb:17:in `each_python'
/usr/local/Library/Taps/homebrew/homebrew-python/matplotlib.rb:189:in `block in <class:Matplotlib>'
/usr/local/Library/Homebrew/formula.rb:1284:in `block in run_test'
…snip…
```

**Comment by bfontaine** [comment]
Thank you @tdsmith; it’s 2am here, time to go :zzz: :smile:

**Comment by tdsmith** [comment]
Oh! It's just timing out: `execution expired`

This is probably good to pull.

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by tdsmith** [comment]
Oops, forgot completely.

**Pull request closed without merging**
