### PR TITLE
scipy: bump for gcc6

### PR DESCRIPTION
**Pull request by claudiodsf**
see #303

### CODE REVIEW

**Comment by bzz** [comment]
Does this fix the scipy build on gcc 6?

**Comment by claudiodsf** [comment]
@bzz This just triggers a recompilation, which fixes the problem. I ha uno problems in compiling against gcc 6. If you have such problems, then it is definitively a different issue.

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
Thanks for the PR; sorry for the delay!

**Comment by claudiodsf** [comment]
@tdsmith No problem 😉

**Pull request closed without merging**
