### PR TITLE
pillow 3.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by maxnordlund** [comment]
I've looked into the test failures, and run them locally as well to make sure they reproduce (see #323 for why that can be the case). It seems to be a problem with freetype 2.7, see https://github.com/python-pillow/Pillow/issues/2116 and frankly that is way out of scope to be fixed here.

The question is then, merge this with failing tests or wait for another patch.

**Comment by ilovezfs** [comment]
Does it not happen with freetype 2.6.5? We could vendor that in I guess …

**Comment by tdsmith** [comment]
Sounds like we should ignore the failures to me.

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
