### PR TITLE
Pillow 3.3.0

### PR DESCRIPTION
**Pull request by maxnordlund**
Remove fix for https://github.com/Homebrew/homebrew-python/issues/190 since it has been fixed upstream. I've tested this locally for both python 2 and 3, and it builds just fine.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The commented out openjpeg option causes audit failure. Also, it looks like that issue is actually now resolved, per the comment. https://github.com/python-pillow/Pillow/issues/767

**Comment by maxnordlund** [comment]
Yeah, but should probably be done in an separate PR.

**Comment by ilovezfs** [comment]
Not if it was fixed in this particular version, and not if it causes current audit failure.

**Comment by maxnordlund** [comment]
Not the JPEG200 one, just the setup replace for Tcl/Tk.

**Comment by maxnordlund** [comment]
For reference it was disabled in 2014, e57723a2, and will need much more testing then just a simple version bump.

**Comment by tdsmith** [comment]
Can you point to the fix for the Tcl issue?

**Comment by maxnordlund** [comment]
This is the issue https://github.com/Homebrew/homebrew-python/issues/190, and the https://github.com/python-pillow/Pillow/pull/1932 PR fixed it.

**Comment by tdsmith** [comment]
Very nice, thanks!

**Pull request closed without merging**
