### PR TITLE
matplotlib: use :tex

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by tdsmith** [comment]
I think I remember matplotlib specifically wants `dvipng` which isn't included in BasicTeX, so this check is helpful as written though the error message could be improved, but I could be wrong.

**Comment by xu-cheng** [comment]
You are right. I just checked BasicTeX doesn't include `dvipng`. I have add it back as a separate requirement.

**Comment by xu-cheng** [comment]
@tdsmith Good to be merged?

**Comment by tdsmith** [comment]
Yeah, go for it. :+1:

**Pull request closed without merging**
