### PR TITLE
numpy 1.10.0

### PR DESCRIPTION
**Pull request by jiegec**

### CODE REVIEW

**Comment by tdsmith** [comment]
The test_weighting scipy test error looks real; know anything about that?

**Comment by jiegec** [comment]
@tdsmith So weird. The test is passed in el_capitan in jenkins, but the test failed in my El Capitan.

**Comment by tdsmith** [comment]
I expect it passed on Jenkins because scipy isn't bottled for El Capitan yet and the bot only tests bottled dependents.

**Comment by tdsmith** [comment]
Seems like the test is wrong: see https://github.com/numpy/numpy/issues/6120 and https://github.com/scipy/scipy/issues/5173.

**Comment by jiegec** [comment]
Then we have to wait for the next release of scipy....

**Pull request closed without merging**
