### PR TITLE
pysvn 1.9.2 (new formula)

### PR DESCRIPTION
**Pull request by IlyaSemenov**
`pysvn` is not available via `pip`, so I made a formula for it.

This PR superseded https://github.com/Homebrew/homebrew-core/pull/1106

### CODE REVIEW

**Comment by IlyaSemenov** [comment]
I don't understand why the build is marked as failed. If you click "Details" it says "Test Result (no failures)" and then if you drill down all 25 tests for every platform are marked as passed.

**Comment by tdsmith** [comment]
Looks reasonable!; can `make clean` run unconditionally?

**Comment by IlyaSemenov** [comment]
@tdsmith it used to be run unconditionally, but @DomT4 wanted it to be smarter, see this thread:
https://github.com/Homebrew/homebrew-core/pull/1106#discussion-diff-63085308

**Comment by tdsmith** [comment]
¯\\\_(ツ)\_/¯

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
Thanks for your pull request! :tada: Homebrew thrives because of contributions like this one. Sorry for the delay!

**Comment by DomT4** [comment]
> @tdsmith it used to be run unconditionally, but @DomT4 wanted it to be smarter, see this thread:
Homebrew/homebrew-core#1106 (diff)

Python is pretty much Tim's tap exclusively, so feel free to throw my advice/request out of the window in this tap.

**Pull request closed without merging**
