### PR TITLE
scipy 0.15.1

### PR DESCRIPTION
**Pull request by joernhees**
patching for #178 removed as now in upstream.

tested on Mac OS X 10.9.5, default flags:
```
Ran 17005 tests in 193.174s

OK (KNOWNFAIL=96, SKIP=1183)
Out[3]: <nose.result.TextTestResult run=17005 errors=0 failures=0>
```

### CODE REVIEW

**Comment by joernhees** [comment]
maybe we should also include running `find /usr/local/lib/python2.7/site-packages/scipy -name '*.pyc' -delete` cause people who upgrade [might run into problems otherwise](https://joernhees.de/blog/2014/02/25/scientific-python-on-mac-os-x-10-9-with-homebrew/#comment-861)?

**Comment by tdsmith** [comment]
Yeah, that does cause confusion. Let's add

```ruby
def post_install
  Language::Python.each_python(build) do |python, version|
    rm_f Dir["#{HOMEBREW_PREFIX}/lib/python#{version}/site-packages/scipy/**/*.pyc"]
  end
end
```

after the `install` method.

**Comment by tdsmith** [comment]
(a comment explaining why would probably be helpful)

**Comment by joernhees** [comment]
@tdsmith like this?

**Comment by tdsmith** [comment]
Yep! Thanks for contributing.

**Comment by joernhees** [comment]
you're welcome ;)

@tdsmith maybe a bit off-topic: any reason you sign off commits like that instead of just merging them?

I ask cause this makes my local branch diverge from upstream:
screen shot 2015-01-22 at 15 06 55

This forces me to rebase on my own signed-off commits locally :-/

**Comment by tdsmith** [comment]
I could've left the version bump commit alone in retrospect but we like to use the "Closes #xxx" notation to link commits to PRs.

**Comment by joernhees** [comment]
k, no worries, just wanted to learn ;)

**Comment by lbenet** [comment]
Tests are not passing after (re)installing scipy (v0.15.1). This is the relevant output that I get after
`brew test scipy -v`:
```
======================================================================
FAIL: test_syr_her (test_blas.TestFBLAS2Simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/tests/test_blas.py", line 316, in test_syr_her
    resz_reverse, rtol=rtol)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([[ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j]], dtype=complex64)
 y: array([[-15.+112.j, -13. +82.j, -11. +52.j,  -9. +22.j],
       [  0.  +0.j, -11. +60.j,  -9. +38.j,  -7. +16.j],
       [  0.  +0.j,   0.  +0.j,  -7. +24.j,  -5. +10.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j,  -3.  +4.j]])

----------------------------------------------------------------------
Ran 17003 tests in 126.957s

FAILED (KNOWNFAIL=96, SKIP=1192, failures=1)
Running unit tests for scipy
NumPy version 1.9.1
NumPy is installed in /usr/local/lib/python2.7/site-packages/numpy
SciPy version 0.15.1
SciPy is installed in /usr/local/lib/python2.7/site-packages/scipy
Python version 2.7.9 (default, Dec 15 2014, 10:17:04) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
nose version 1.3.4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
Error: scipy: failed
Failed executing: python -c import\ scipy;\ assert\ not\ scipy.test().failures
/usr/local/Library/Homebrew/formula.rb:730:in `block in system'
/usr/local/Library/Homebrew/formula.rb:687:in `open'
/usr/local/Library/Homebrew/formula.rb:687:in `system'
/usr/local/Library/Taps/samueljohn/homebrew-python/scipy.rb:88:in `block (2 levels) in <class:Scipy>'
/usr/local/Library/Homebrew/language/python.rb:25:in `call'
/usr/local/Library/Homebrew/language/python.rb:25:in `block in each_python'
/usr/local/Library/Homebrew/language/python.rb:17:in `each'
/usr/local/Library/Homebrew/language/python.rb:17:in `each_python'
/usr/local/Library/Taps/samueljohn/homebrew-python/scipy.rb:87:in `block in <class:Scipy>'
/usr/local/Library/Homebrew/formula.rb:639:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:636:in `run_test'
/usr/local/Library/Homebrew/cmd/test.rb:38:in `block (2 levels) in test'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/cmd/test.rb:37:in `block in test'
/usr/local/Library/Homebrew/cmd/test.rb:15:in `each'
/usr/local/Library/Homebrew/cmd/test.rb:15:in `test'
/usr/local/Library/brew.rb:135:in `<main>'
```

Is this normal behaviour?

**Comment by tdsmith** [comment]
Nope! If you're building against openblas, this may be an openblas bug: https://github.com/scipy/scipy/issues/4453

**Pull request closed without merging**
